# Generated by Django 4.0.6 on 2022-07-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='desc',
            field=models.TextField(max_length=20),
        ),
    ]
