# Generated by Django 4.0.6 on 2022-07-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0002_alter_recipedetails_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipedetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='desc',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recipedetails',
            name='prikey',
            field=models.TextField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
