# Generated by Django 4.0.6 on 2022-07-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipies', '0003_remove_recipedetails_id_alter_recipedetails_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='desc',
            field=models.TextField(max_length=280),
        ),
    ]
